language: generic
sudo: required
services:
  - docker
before_install: 
  - docker build -t roopdock1/docker-fib -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true roopdock1/docker-fib npm run test
after_success:
  - docker build -t roopdock1/docker-client ./client
  - docker build -t roopdock1/docker-nginx ./nginx
  - docker build -t roopdock1/docker-server ./server
  - docker build -t roopdock1/docker-worker ./worker

# Login to the Docker CLI through Travis
- echo "$DOCK_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take these images and push them to docker-hub
- docker push roopdock1/docker-client
- docker push roopdock1/docker-nginx
- docker push roopdock1/docker-server
- docker push roopdock1/docker-worker

# travis configuration for deployment to AWS Beanstalk
# deploy:
#   provider: elasticbeanstalk
#   region: "us-west-2"
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-306476627547"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"